version: '3.8'
services:
  deepwukong:
    build: ./docker/deepwukong
    shm_size: '64g'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - deepwukong_model:/code/models/DeepWukong
      - dataset:/data/dataset/
  deepwukong_without_gpu:
    build: ./docker/deepwukong
    volumes:
      - deepwukong_model:/code/models/DeepWukong
      - dataset:/data/dataset/
volumes:
  dataset:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Dataset
  deepwukong_model:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Experiments/DeepWukong